# Generated by Django 2.2.5 on 2019-11-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='script_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_name', models.CharField(max_length=30)),
                ('dialogue_number', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('character_name', models.CharField(max_length=30)),
                ('dialogue', models.TextField()),
            ],
        ),
    ]
